### ISSUE TITLE
how to support chinese character?

### ISSUE THREAD

**Issue by mrme2014** [aagarwal1012/Image-Steganography-Library-Android#3] opened 2018-11-15 10:40 UTC
i want to use your library to  make my app support to hide secret which may is chinese character

could you  update you  branch?

**Comment by aagarwal1012** [comment] 2018-11-17 08:21
@mrme2014 can you elaborate the problem and where this library is lacking behind?

**Comment by mrme2014** [comment] 2018-11-17 08:23
Currently this library does not support Chinese characters well

Also, in some cases, even pure English characters cannot be restored 100%

**Comment by aagarwal1012** [comment] 2018-11-17 08:32
@mrme2014 
If you won't give me some code or error outputs and other steps to reproduce that problem then how will I be going to fix the problem? Please specify the above. 😸

**Comment by mrme2014** [comment] 2018-11-17 08:35
Ok, now I'm going to give you a couple of Chinese characters, and you copy and paste it into the app input box and encode it into the picture, and then you try to decode it, and you'll see the messy code


You can try these Chinese characters: 中文才是最屌的 o r  中文是最棒棒的

**Comment by rhayes2** [comment] 2018-12-04 05:15
I looked into this, 
Looks like there needs to be base64 encoding on the chars before the flags are adding in the encoding,
Im not sure how this will work with the compression alg

Ill attach a PR of my findings [PR](https://github.com/aagarwal1012/Image-Steganography-Library-Android/pull/6)

**Comment by ucsunup** [comment] 2018-12-31 11:04
@mrme2014 

You can encode the decoded result in UTF-8.

**Comment by rhayes2** [comment] 2019-01-03 18:19
Merged  [PR](https://github.com/aagarwal1012/Image-Steganography-Library-Android/pull/6)

**Closed as completed** 2019-01-03 18:19 UTC
